### ISSUE TITLE
Plot info

### ISSUE THREAD

**Issue by DEQcdonald** [donco/odeqstatusandtrends#17]
Comments:
- It would be great if the pop-up graphs also including stream name, river mile, assessment unit name, and a "save as jpg" option.

**Comment by DEQcdonald** [comment]
Partially addressed with download link in 715ca970601b2c3d69518d6b1e127e104c75ed9c. Still need to add info to plots.

**Comment by DEQcdonald** [comment]
More info added to plots in commit: 83a438ca2c8a78419e4ae1cfdcd35109bbe35725
Have not added river mile or stream name

**Comment by DEQrmichie** [comment]
It is not possible to add river mile and stream name in all cases because it's not often in the stations database. When the stations database has this information more consistently we can revisit this issue. For now I am closing.
