### ISSUE TITLE
Columbia River map includes water quality limited AUs outside of assessment area

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqstatusandtrends#27]
The parameter maps for the Columbia River show a number of water quality limited watershed units and reach segments for areas adjacent to the Columbia River. These should not be shown for the Columbia River map. I think this happens because AUs are being selected based on HUC12. 

For the Columbia River I suggest we filter based on only the AU IDs for the Columbia River.  Maybe we should consider attributing the AU features according to the webmap units so this can be done for all maps. As an interim step I pulled out all the Columbia River AU waterbodies and saved the feature in the GIS folder under Assessment_Units.gdb

**Comment by DEQcdonald** [comment]
Addressed in commit: 630f3c0bcd7801b826ab7dc982ae5055ef76005c

**Comment by DEQrmichie** [comment]
This issue still persists in the static maps that are in the word report.

**Comment by DEQcdonald** [comment]
This issue has been confirmed as fixed in the 2020 report.
