### ISSUE TITLE
TMDL info in web map station pop-ups

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqstatusandtrends#30]
It would be very helpful to have the following TMDL target information added into the webmap station pop-ups:

* TMDL target value with units converted to mg/L (e.g. 0.0071 mg/L)
* Applicable Period
* TMDL document reference

It would be formatted and named the same way as shown in the Report. You might be able to borrow the code form there.

The table in the pop-up might look something like this:

Pollutant | Target | Statistical Base | Applicable Period | TMDL
-- | -- | -- | -- | --
Total Phosphorus, mixed forms | 0.0071 mg/L | single sample |  Jan 01 - Dec 31  | Tenmile Lakes TMDL (DEQ 2007)

**Comment by DEQcdonald** [comment]
This enhancement has been added within the 2020 report.
