### ISSUE TITLE
DO status not matching excursion results

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqstatusandtrends#32]
The DO status at station 10508-ORDEQ in the Deschutes does not match the water quality results. There are multiple periods with non attaining status but there are no excursions in these periods based on the results in data_assessed. Something might be off with the DO status logic.

**Comment by DEQcdonald** [comment]
Addressed in commit: 9ab5fc9aa069e4ee6b2be88e5f49c3cfd84f5423

**Comment by DEQcdonald** [comment]
Confirmed.
