### ISSUE TITLE
Change webmap lR layer name and color

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqstatusandtrends#36]
The IR layer in the webmaps is called:

"WQ Listed Assessment Units"

Because this layer also includes Attaining and Potential Concern results the name is not accurate. I think it should be changed to something like

"2018/2020 303(d)/305(b) IR Status"

Also we should consider changing the color from red to something more neutral since red evokes more of a WQL status. Maybe purple? Open to suggestions.

**Comment by DEQcdonald** [comment]
Addressed in commit: baaec5d8346fdb26932a89f3a31606e34281945d
Confirm on re-run

**Comment by DEQcdonald** [comment]
Confirmed.
