### ISSUE TITLE
Updates to Non-spawning line on DO Plots 

### ISSUE THREAD

**Issue by rmichie** [donco/odeqstatusandtrends#5]
The non-spawning line applies year-round so it should be renamed to year-round.

Also suggest updating the plot so the "year-round" line is continuous over the entire plotting period instead of breaking during the spawning period. 

Suggest changing the spawning period line to a non-dashed line so it is easier to see. The fill color behind the line might also be updated so it is the same dark gray as in the plot.

**Comment by DEQcdonald** [comment]
Addressed in commit 19bf02f8c154d06c1fffb94e5da7427a9530dff0
