### ISSUE TITLE
Bug in plotting of temperature trend

### ISSUE THREAD

**Issue by rmichie** [donco/odeqstatusandtrends#6]
There appears to be a bug in the temperature plotting or trend related code. Some of the plots show a temperature trend line when it appears there would not be sufficient amount of data to calculate trend. An example is station 10508-ORDEQ in the Upper Deschutes Subbasin.

![temp_10508-ORDEQ](https://user-images.githubusercontent.com/6916030/70668651-07e66d00-1c29-11ea-90f6-ac515235ff81.jpeg).

**Comment by DEQcdonald** [comment]
Addressed via state_param_summary R script
