### ISSUE TITLE
Definition of status and trend report terms

### ISSUE THREAD

**Issue by rmichie** [donco/odeqstatusandtrends#7]
We can add new definitions as needed:

Result - a water quality observation or a calculated observation in the statistical units of the water quality criteria (i.e. geomean or 7-day average daily maximum).

Excursion - Occurs when a result is worse than the water quality standard or TMDL target.

Attaining - When results demonstrate attainment of the water quality criteria or TMDL target.

Not Attaining - When results do not attain the water quality criteria or TMDL target.

Insufficient Data - When there are results available but the results do not meet QA/QC objectives including minimum Data Quality Levels (DQLs); or the results do not meet minimum requirements to evaluate attainment of the water quality criteria or TMDL target (status), or to assess trend.

Unassessed -  When there are no results available or when there are results but no numeric water quality criteria or TMDL target to evaluate attainment against.

**Comment by DEQcdonald** [comment]
Tweaked a bit, but addressed within the 2020 report language and methodology.
