### ISSUE TITLE
WQP data quality identifiers

### ISSUE THREAD

**Issue by DEQcdonald** [donco/odeqstatusandtrends#8]
Need to determine the appropriate identifiers to use for WQP data.

Examples:
U, UJ, NA, "Accepted", "Final"...

**Comment by rmichie** [comment]
Here are the Water Quality Portal DQL definitions:

Result Status Identifier
http://cdx.epa.gov/wqx/download/DomainValues/ResultStatus_CSV.zip

Result Measure Qualifier
http://cdx.epa.gov/wqx/download/DomainValues/ResultMeasureQualifier_CSV.zip

All from this page:
https://www.waterqualitydata.us/portal_userguide/

**Comment by DEQcdonald** [comment]
Addressed within data cleaning.
