### ISSUE TITLE
Add functions to summarize data for report Appendix

### ISSUE THREAD

**Issue by rmichie** [donco/odeqstatusandtrends#9]
We need to add functions that will summarize data similar to what used to be included in the Appendix of the old reports. I think there needs to be three new functions that output the following tables:

1. Summary table of all the unique organizations that collected data used in the analysis (organized by Basin).

| Basin | Sampling Organization | Number of Results | Unique Stations | NA Results | Unique Comments |
| -- | -- | -- | -- | -- | -- |

2. Summary of all unique organizations that collected data at each station for each parameter that had a status or trend result.

| Station ID | Station Name | Basin | Subbasin | Assessment Unit ID | Parameter | Sampling Organizations |
| -- | -- | -- | -- | -- | -- | -- |

3.  Number of results per year for monitoring stations that fit the criteria to assess status or trends.

| Station ID | Station Name | Basin | Subbasin | Assessment Unit ID | Parameter | 1999 | ... | 2018 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | 

The functions should be called and outputs added as a worksheet in the xlsx output in this code [here](https://github.com/donco/st_report_files/blob/master/state_param_summary2.R#L303-L328).

**Comment by DEQcdonald** [comment]
Addressed in commit
https://github.com/donco/st_report_files/commit/54afefe8b9eab849ad1a07341cc624eaeac88201
